### PR TITLE
Kan 7 ahmad's test code

### PR DESCRIPTION
**Pull request by nagalil-hanoj-hteal3**

### CODE REVIEW

**Comment by nagalil-hanoj-hteal3** [comment]
merge please

**Review by Soulpuncher1234 — CHANGES_REQUESTED** [review]
Send to main branch ok

**Review by nagalil-hanoj-hteal3 — COMMENTED** [review]
nice

**Review by Soulpuncher1234 — CHANGES_REQUESTED** [review]
Send to main branch ok

**Pull request closed without merging**
